server:
    port: 9007
    
logging:
    file: fileUploadPractice-backend.log
    level:
        com.jbarillasgarcia.fileUploadPractice: DEBUG
        
fileUpload:
    fileDirectory: /tmp
    
spring:
    servlet:
        multipart:        
            max-file-size: 20MB
            max-request-size: 20MB        